name: {{name}}
description: {{description}}
version: {{version}}

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: {{flame-version}}{{#extra-packages}}
  {{name}}: {{version}}{{/extra-packages}}

dev_dependencies:
  flame_lint: {{flame-lint-version}}
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: false