name: ignite_cli
description: Ignite your projects with flame; a CLI scaffolding tool to create and setup your Flame projects
version: 0.4.0
repository: https://github.com/flame-engine/ignite-cli

# Add the bin/ignite.dart script to the scripts pub installs
executables:
  ignite:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  completion: ^1.0.0
  io: ^1.0.0
  mason: ^0.0.1-dev.55
  path: ^1.8.0
  process_run: ^0.12.1
  prompts: ^2.0.0
  yaml: ^3.1.0

dev_dependencies:
  test: ^1.16.0
  dart_code_metrics: ^3.2.2
  dartdoc: ^0.42.0
  pedantic: ^1.11.0
