name: ignite_cli
description: Ignite your projects with flame; a CLI scaffolding tool to create and setup your Flame projects
version: 0.5.0
repository: https://github.com/flame-engine/ignite-cli

# Add the bin/ignite.dart script to the scripts pub installs
executables:
  ignite:

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.1.0
  completion: ^1.0.0
  dartlin: ^0.6.3
  http: ^0.13.4
  io: ^1.0.3
  mason: ^0.1.0-dev.31
  path: ^1.8.2
  process_run: ^0.12.3+2
  prompts: ^2.0.0
  yaml: ^3.1.0

dev_dependencies:
  dartdoc: ^0.42.0
  flame_lint: ^0.1.1
  pedantic: ^1.11.0
  test: ^1.16.0
