name: ignite_cli
description: Ignite your projects with flame; a CLI scaffolding tool to create and setup your Flame projects
version: 0.6.0
repository: https://github.com/flame-engine/ignite-cli

# Add the bin/ignite.dart script to the scripts pub installs
executables:
  ignite:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  charcode: ^1.3.1
  completion: ^1.0.1
  dartlin: ^0.6.3
  http: ^1.3.0
  io: ^1.0.4
  mason: ^0.1.0-dev.51
  path: ^1.9.0
  process_run: ^1.2.4
  prompts: ^2.0.0
  yaml: ^3.1.2

dev_dependencies:
  dartdoc: ^8.0.2
  flame_lint: ^1.3.0
  mason_cli: ^0.1.0-dev.53
  test: ^1.24.9