name: ignite_cli
description: Ignite your projects with flame; a CLI scaffolding tool to create and setup your Flame projects
version: 0.6.0
repository: https://github.com/flame-engine/ignite-cli

# Add the bin/ignite.dart script to the scripts pub installs
executables:
  ignite:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.7.0
  charcode: ^1.4.0
  completion: ^1.0.1
  dartlin: ^0.6.3
  http: ^1.3.0
  io: ^1.0.5
  mason: ^0.1.1
  path: ^1.9.1
  process_run: ^1.2.4
  prompts: ^2.0.0
  yaml: ^3.1.3

dev_dependencies:
  dartdoc: ^8.0.2
  flame_lint: ^1.3.0
  mason_cli: ^0.1.2
  test: ^1.24.9