name: {{name}}
description: {{description}}
version: {{version}}

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  {{#extra-dependencies}}
  {{name}}: {{version}}
  {{/extra-dependencies}}

dev_dependencies:
  {{#extra-dev-dependencies}}
  {{name}}: {{version}}
  {{/extra-dev-dependencies}}
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: false