name: {{name}}
description: {{description}}
version: {{version}}

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:{{#extra-dependencies}}
  {{name}}: {{version}}{{/extra-dependencies}}
  flutter:
    sdk: flutter

dev_dependencies:{{#extra-dev-dependencies}}
  {{name}}: {{version}}{{/extra-dev-dependencies}}
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: false